version: '3.8'

services:
  api-gateway:
    image: devopsfaith/krakend:2.9.1
    container_name: krakend-api-gateway
    ports:
      - "8081:8080" 
      - "9091:9091"
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json:ro 
    environment:
      - KRAKEND_PORT=8080
    networks:
          - lab

networks:
  lab:
    external: true