version: '3.8'

services:
  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - lab

volumes:
  grafana-data:

networks:
  lab:
    external: true